# Generated by Django 3.0.8 on 2020-07-26 16:49

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назва')),
                ('main_image', models.ImageField(upload_to='uploads/main_images', verbose_name='Головне фото')),
                ('text', models.CharField(max_length=10000, verbose_name='Текст статті')),
                ('slug', autoslug.fields.AutoSlugField(allow_unicode=True, editable=False, max_length=200, populate_from='title', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Пости',
                'ordering': ('id',),
            },
        ),
    ]
