# Generated by Django 3.0.8 on 2020-07-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200726_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_text',
            field=models.CharField(default='smth', max_length=150, verbose_name='Текст-прев\\`ю'),
            preserve_default=False,
        ),
    ]
