# Generated by Django 3.0.8 on 2020-09-13 14:48

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200912_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва')),
                ('slug', autoslug.fields.AutoSlugField(allow_unicode=True, editable=False, max_length=200, populate_from='title', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Теги',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, editable=True, max_length=200, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview_text',
            field=models.CharField(max_length=120, verbose_name='Текст-прев\\`ю'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='core.Tags', verbose_name='Теги'),
        ),
    ]
