# Generated by Django 3.0.8 on 2020-09-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_text',
            field=models.CharField(max_length=150, verbose_name='Текст-прев\\`ю'),
        ),
    ]
