# Generated by Django 3.0.8 on 2020-09-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200913_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=20000, verbose_name='Текст'),
        ),
    ]
