# Generated by Django 3.0.8 on 2020-09-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200913_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_text',
            field=models.CharField(max_length=300, verbose_name='Текст-прев\\`ю'),
        ),
    ]
