# Generated by Django 3.0.8 on 2020-10-16 10:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200913_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-creating_date',), 'verbose_name_plural': 'Пости'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, editable=False, max_length=200, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, editable=True, max_length=200, populate_from='title', unique=True),
        ),
    ]
