# Generated by Django 3.0.8 on 2020-10-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='Категорія', max_length=100, verbose_name="Опис, що з'явиться при наведенні курсору"),
            preserve_default=False,
        ),
    ]
