# Generated by Django 3.0.8 on 2020-10-20 12:54

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201020_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, editable=False, populate_from='create_slug', unique=True),
        ),
    ]
