# Generated by Django 3.0.8 on 2020-10-22 09:17

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_post_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, editable=True, max_length=30, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='star',
            field=models.BooleanField(default=False, verbose_name='Топ-пости(3)'),
        ),
    ]
