# Generated by Django 3.0.8 on 2020-12-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201101_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='uploads/main_images', verbose_name='Головне фото'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Текст-прев\\`ю'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tags', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, max_length=20000, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Назва'),
        ),
    ]
