# Generated by Django 3.0.8 on 2020-12-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201225_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, max_length=20000, null=True, verbose_name='Текст'),
        ),
    ]
