# Generated by Django 3.0.8 on 2020-12-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20201225_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(upload_to='uploads/main_images', verbose_name='Головне фото'),
        ),
    ]
